{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "HTTP Request Duration (p95)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(gamehub_http_server_request_duration_seconds_bucket[1m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "gamehub_http_server_requests_total{path!=\"/metrics\", job=\"main_service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "__auto" },
    {}
   ]
  },
  {
   "title": "Number of Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 24 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage (per second)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 24 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alert table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 31 },
   "targets": [
    {
     "expr": "ALERTS{job=\"main_service\", alertstate=~\"firing|pending\"}\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}