name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        options: >-
          --health-cmd="pg_isready -U test"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Wait for Postgres to be ready

        run: |
          for i in $(seq 1 10); do
            pg_isready -h localhost -p 5432 -U test && break
            sleep 1
          done

      - name: Run unit tests
        run: |
          go test -short -timeout 30s ./internal/usecase

      - name: Run integration tests

        run: |
          go test -timeout 2m ./integration-test

      - name: Run all other tests
        run: |
          go test -timeout 2m ./...
